### ISSUE TITLE
LEX To-Do list

### ISSUE THREAD

**Issue by SirCxyrtyx** [ME3Tweaks/LegendaryExplorer#253]
- [x] ObjectInfos for LE don't have the SequenceObjectInfo in them. The LE{gamenum}UnrealObjectInfo::generateInfo functions for each LE game need to be changed to do two passes of the files: one to build the Classes and Structs Dictionaries, and then one to build the SequenceObjects Dictionary. This is because building SequenceObjects requires Classes and Structs to already be filled.
- [ ] Test cases for relinker
- [ ] Check all usages of MEGame
- [x] "CookedPC/CookedPCConsole" pathing checks (should be using MEGame.CookedDirName() now)
- [x] Hex Converter should be on .NET 4.8, not 5, it will not work in stable builds unless we want to ship an additional 70MB. Hex Converter gains no benefits from .NET 5 (plus it rarely, if ever, updates)
- [x] Drop SharpDX.LEX now that .NET 5 has Vector classes as suggested by Benji?
- [ ] Port in a new ASI Manager. This might need to be done post-release as ME3X ASI Manager is based on old ME3CMM code and does not check for duplicates like M3 code does, but M3 code depends on a few other core ME3Tweaks classes that need to be split into ME3TweaksCore
- [ ] TFC Compactor needs a solution since we don't have access to MEM for LE that has feature set we need. Texture Studio partially accomplishes this, with some work this could probably cover OT/LE. LE version needs to not check against official DLC since it is expected they will always be present
- [x] Replacing textures probably could initiate a busy host since textures take significantly longer in LE, especially BC7. We should probably benchmark to see how long it takes
- [x] Implement AFC compactor for LE
- [ ] Game Interop for LE (6.1?)
- [x] Add saved sequence layout json support to LE
- [x] General settings dialog for main window. Ideal would be something autogenerated from AppSettings, but the four game paths and transparency option for the main window would probably be enough for the initial release
- [x] Rename Interpreter to Properties
- [x] Initial onboarding wizard, where game directories are selected, etc
- [x] Implement Soundpanel miniplayer for things like FaceFX Editor and Dialogue Editor
- [ ] Test shader porting
- [ ] Improve texture replacement UX

**Comment by Kinkojiro** [comment]
- [x] Fix Hex converter issue (asking for .net)

**Comment by henbagle** [comment]
Main Window To-Do: #254

- [x] General help window with links to tutorials, discord server, etc
- [ ] Rewrite Plot Editor (6.1)
