### ISSUE TITLE
LEX Main Window To-do

### ISSUE THREAD

**Issue by henbagle** [ME3Tweaks/LegendaryExplorer#254]
- [x] Hint to let the user know how to set favorites
- [x] Panel somewhere to show tool description, recent files? MG does not want a flyout.
- [x] Help window
- [x] Selected tab is highlighted
- ~~Default favorites - Same as Develop Mods section in old main window~~   **Currently wouldn't work well with the favorite hint, toolset defaults to 'Core Tools' tab anyway**
- [x] Favorites saved using new settings framework
- [x] Get rid of tooltips on tool icons?
- [x] Option to disable transparency
- [x] Display toolset version (under top bar about button?)
- [x] Settings window - autogenerated from app settings?
- [ ] Add more information to Help Center
- [ ] Make ToolPanel less abstracted
